var q=null;window.PR_SHOULD_USE_CONTINUATION=!0;
(function(){function T(d){function r(e){var a=e.charCodeAt(0);if(92!==a)return a;var b=e.charAt(1);return(a=x[b])?a:"0"<=b&&"7">=b?parseInt(e.substring(1),8):"u"===b||"x"===b?parseInt(e.substring(2),16):e.charCodeAt(1)}function m(e){if(32>e)return(16>e?"\\x0":"\\x")+e.toString(16);e=String.fromCharCode(e);if("\\"===e||"-"===e||"["===e||"]"===e)e="\\"+e;return e}function n(e){var a=e.substring(1,e.length-1).match(/\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\S\s]|[^\\]/g);e=
[];for(var b=[],f="^"===a[0],c=f?1:0,g=a.length;c<g;++c){var h=a[c];if(/\\[bdsw]/i.test(h))e.push(h);else{h=r(h);var v;c+2<g&&"-"===a[c+1]?(v=r(a[c+2]),c+=2):v=h;b.push([h,v]);65>v||122<h||(65>v||90<h||b.push([Math.max(65,h)|32,Math.min(v,90)|32]),97>v||122<h||b.push([Math.max(97,h)&-33,Math.min(v,122)&-33]))}}b.sort(function(C,D){return C[0]-D[0]||D[1]-C[1]});a=[];h=[NaN,NaN];for(c=0;c<b.length;++c)g=b[c],g[0]<=h[1]+1?h[1]=Math.max(h[1],g[1]):a.push(h=g);b=["["];f&&b.push("^");b.push.apply(b,e);
for(c=0;c<a.length;++c)g=a[c],b.push(m(g[0])),g[1]>g[0]&&(g[1]+1>g[0]&&b.push("-"),b.push(m(g[1])));b.push("]");return b.join("")}function z(e){for(var a=e.source.match(/\[(?:[^\\\]]|\\[\S\s])*]|\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\\d+|\\[^\dux]|\(\?[!:=]|[()^]|[^()[\\^]+/g),b=a.length,f=[],c=0,g=0;c<b;++c){var h=a[c];"("===h?++g:"\\"===h.charAt(0)&&(h=+h.substring(1))&&h<=g&&(f[h]=-1)}for(c=1;c<f.length;++c)-1===f[c]&&(f[c]=++y);for(g=c=0;c<b;++c)h=a[c],"("===h?(++g,void 0===f[g]&&(a[c]="(?:")):"\\"===
h.charAt(0)&&(h=+h.substring(1))&&h<=g&&(a[c]="\\"+f[g]);for(g=c=0;c<b;++c)"^"===a[c]&&"^"!==a[c+1]&&(a[c]="");if(e.ignoreCase&&u)for(c=0;c<b;++c)h=a[c],e=h.charAt(0),2<=h.length&&"["===e?a[c]=n(h):"\\"!==e&&(a[c]=h.replace(/[A-Za-z]/g,function(v){v=v.charCodeAt(0);return"["+String.fromCharCode(v&-33,v|32)+"]"}));return a.join("")}for(var y=0,u=!1,p=!1,w=0,k=d.length;w<k;++w){var l=d[w];if(l.ignoreCase)p=!0;else if(/[a-z]/i.test(l.source.replace(/\\u[\da-f]{4}|\\x[\da-f]{2}|\\[^UXux]/gi,""))){u=!0;
p=!1;break}}var x={b:8,t:9,n:10,v:11,f:12,r:13},t=[];w=0;for(k=d.length;w<k;++w){l=d[w];if(l.global||l.multiline)throw Error(""+l);t.push("(?:"+z(l)+")")}return RegExp(t.join("|"),p?"gi":"g")}function U(d){function r(k){switch(k.nodeType){case 1:if(m.test(k.className))break;for(var l=k.firstChild;l;l=l.nextSibling)r(l);l=k.nodeName;if("BR"===l||"LI"===l)n[u]="\n",y[u<<1]=z++,y[u++<<1|1]=k;break;case 3:case 4:l=k.nodeValue,l.length&&(l=w?l.replace(/\r\n?/g,"\n"):l.replace(/[\t\n\r ]+/g," "),n[u]=l,
y[u<<1]=z,z+=l.length,y[u++<<1|1]=k)}}var m=/(?:^|\s)nocode(?:\s|$)/,n=[],z=0,y=[],u=0,p;d.currentStyle?p=d.currentStyle.whiteSpace:window.getComputedStyle&&(p=document.defaultView.getComputedStyle(d,q).getPropertyValue("white-space"));var w=p&&"pre"===p.substring(0,3);r(d);return{a:n.join("").replace(/\n$/,""),c:y}}function J(d,r,m,n){r&&(d={a:r,d:d},m(d),n.push.apply(n,d.e))}function F(d,r){function m(u){for(var p=u.d,w=[p,"pln"],k=0,l=u.a.match(z)||[],x={},t=0,e=l.length;t<e;++t){var a=l[t],b=
x[a],f=void 0;if("string"===typeof b)var c=!1;else{var g=n[a.charAt(0)];if(g)f=a.match(g[1]),b=g[0];else{for(c=0;c<y;++c)if(g=r[c],f=a.match(g[1])){b=g[0];break}f||(b="pln")}!(c=5<=b.length&&"lang-"===b.substring(0,5))||f&&"string"===typeof f[1]||(c=!1,b="src");c||(x[a]=b)}g=k;k+=a.length;if(c){c=f[1];var h=a.indexOf(c),v=h+c.length;f[2]&&(v=a.length-f[2].length,h=v-c.length);b=b.substring(5);J(p+g,a.substring(0,h),m,w);J(p+g+h,c,K(b,c),w);J(p+g+v,a.substring(v),m,w)}else w.push(p+g,b)}u.e=w}var n=
{},z;(function(){for(var u=d.concat(r),p=[],w={},k=0,l=u.length;k<l;++k){var x=u[k],t=x[3];if(t)for(var e=t.length;0<=--e;)n[t.charAt(e)]=x;x=x[1];t=""+x;w.hasOwnProperty(t)||(p.push(x),w[t]=q)}p.push(/[\S\s]/);z=T(p)})();var y=r.length;return m}function B(d){var r=[],m=[];d.tripleQuotedStrings?r.push(["str",/^(?:'''(?:[^'\\]|\\[\S\s]|''?(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\S\s]|""?(?=[^"]))*(?:"""|$)|'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$))/,q,"'\""]):d.multiLineStrings?r.push(["str",
/^(?:'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$)|`(?:[^\\`]|\\[\S\s])*(?:`|$))/,q,"'\"`"]):r.push(["str",/^(?:'(?:[^\n\r'\\]|\\.)*(?:'|$)|"(?:[^\n\r"\\]|\\.)*(?:"|$))/,q,"\"'"]);d.verbatimStrings&&m.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,q]);var n=d.hashComments;n&&(d.cStyleComments?(1<n?r.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,q,"#"]):r.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\n\r]*)/,q,"#"]),m.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,
q])):r.push(["com",/^#[^\n\r]*/,q,"#"]));d.cStyleComments&&(m.push(["com",/^\/\/[^\n\r]*/,q]),m.push(["com",/^\/\*[\S\s]*?(?:\*\/|$)/,q]));d.regexLiterals&&m.push(["lang-regex",/^(?:^^\.?|[!+-]|!=|!==|#|%|%=|&|&&|&&=|&=|\(|\*|\*=|\+=|,|-=|->|\/|\/=|:|::|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|[?@[^]|\^=|\^\^|\^\^=|{|\||\|=|\|\||\|\|=|~|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\s*(\/(?=[^*/])(?:[^/[\\]|\\[\S\s]|\[(?:[^\\\]]|\\[\S\s])*(?:]|$))+\/)/]);(n=d.types)&&
m.push(["typ",n]);d=(""+d.keywords).replace(/^ | $/g,"");d.length&&m.push(["kwd",RegExp("^(?:"+d.replace(/[\s,]+/g,"|")+")\\b"),q]);r.push(["pln",/^\s+/,q," \r\n\t\u00a0"]);m.push(["lit",/^@[$_a-z][\w$@]*/i,q],["typ",/^(?:[@_]?[A-Z]+[a-z][\w$@]*|\w+_t\b)/,q],["pln",/^[$_a-z][\w$@]*/i,q],["lit",/^(?:0x[\da-f]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+-]?\d+)?)[a-z]*/i,q,"0123456789"],["pln",/^\\[\S\s]?/,q],["pun",/^.[^\s\w"-$'./@\\`]*/,q]);return F(r,m)}function L(d,r){function m(a){switch(a.nodeType){case 1:if(z.test(a.className))break;
if("BR"===a.nodeName)n(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)m(a);break;case 3:case 4:if(w){var b=a.nodeValue,f=b.match(y);if(f){var c=b.substring(0,f.index);a.nodeValue=c;(b=b.substring(f.index+f[0].length))&&a.parentNode.insertBefore(u.createTextNode(b),a.nextSibling);n(a);c||a.parentNode.removeChild(a)}}}}function n(a){function b(c,g){var h=g?c.cloneNode(!1):c,v=c.parentNode;if(v){v=b(v,1);var C=c.nextSibling;v.appendChild(h);for(var D=C;D;D=C)C=
D.nextSibling,v.appendChild(D)}return h}for(;!a.nextSibling;)if(a=a.parentNode,!a)return;a=b(a.nextSibling,0);for(var f;(f=a.parentNode)&&1===f.nodeType;)a=f;k.push(a)}var z=/(?:^|\s)nocode(?:\s|$)/,y=/\r\n?|\n/,u=d.ownerDocument,p;d.currentStyle?p=d.currentStyle.whiteSpace:window.getComputedStyle&&(p=u.defaultView.getComputedStyle(d,q).getPropertyValue("white-space"));var w=p&&"pre"===p.substring(0,3);for(p=u.createElement("LI");d.firstChild;)p.appendChild(d.firstChild);for(var k=[p],l=0;l<k.length;++l)m(k[l]);
r===(r|0)&&k[0].setAttribute("value",r);var x=u.createElement("OL");x.className="linenums";var t=Math.max(0,r-1|0)||0;l=0;for(var e=k.length;l<e;++l)p=k[l],p.className="L"+(l+t)%10,p.firstChild||p.appendChild(u.createTextNode("\u00a0")),x.appendChild(p);d.appendChild(x)}function A(d,r){for(var m=r.length;0<=--m;){var n=r[m];H.hasOwnProperty(n)?window.console&&console.warn("cannot override language handler %s",n):H[n]=d}}function K(d,r){d&&H.hasOwnProperty(d)||(d=/^\s*</.test(r)?"default-markup":"default-code");
return H[d]}function M(d){var r=d.g;try{var m=U(d.h),n=m.a;d.a=n;d.c=m.c;d.d=0;K(r,n)(d);var z=/\bMSIE\b/.test(navigator.userAgent);r=/\n/g;var y=d.a,u=y.length;m=0;var p=d.c,w=p.length;n=0;var k=d.e,l=k.length;d=0;k[l]=u;var x,t;for(t=x=0;t<l;)k[t]!==k[t+2]?(k[x++]=k[t++],k[x++]=k[t++]):t+=2;l=x;for(t=x=0;t<l;){for(var e=k[t],a=k[t+1],b=t+2;b+2<=l&&k[b+1]===a;)b+=2;k[x++]=e;k[x++]=a;t=b}for(k.length=x;n<w;){var f=p[n+2]||u,c=k[d+2]||u;b=Math.min(f,c);var g=p[n+1],h;if(1!==g.nodeType&&(h=y.substring(m,
b))){z&&(h=h.replace(r,"\r"));g.nodeValue=h;var v=g.ownerDocument,C=v.createElement("SPAN");C.className=k[d+1];var D=g.parentNode;D.replaceChild(C,g);C.appendChild(g);m<f&&(p[n+1]=g=v.createTextNode(y.substring(b,f)),D.insertBefore(g,C.nextSibling))}m=b;m>=f&&(n+=2);m>=c&&(d+=2)}}catch(I){"console"in window&&console.log(I&&I.stack?I.stack:I)}}var E=["break,continue,do,else,for,if,return,while"],G=[[E,"auto,case,char,const,default,double,enum,extern,float,goto,int,long,register,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],
"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],N=[G,"alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,dynamic_cast,explicit,export,friend,inline,late_check,mutable,namespace,nullptr,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],O=[G,"abstract,boolean,byte,extends,final,finally,implements,import,instanceof,null,native,package,strictfp,super,synchronized,throws,transient"],
P=[O,"as,base,by,checked,decimal,delegate,descending,dynamic,event,fixed,foreach,from,group,implicit,in,interface,internal,into,is,lock,object,out,override,orderby,params,partial,readonly,ref,sbyte,sealed,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,var"];G=[G,"debugger,eval,export,function,get,null,set,undefined,var,with,Infinity,NaN"];var Q=[E,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],
R=[E,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"];E=[E,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"];var S=/^(DIR|FILE|vector|(de|priority_)?queue|list|stack|(const_)?iterator|(multi)?(set|map)|bitset|u?(int|float)\d*)/,V=/\S/,W=B({keywords:[N,P,G,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END"+
Q,R,E],hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),H={};A(W,["default-code"]);A(F([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\S\s]*?(?:--\x3e|$)/],["lang-",/^<\?([\S\s]+?)(?:\?>|$)/],["lang-",/^<%([\S\s]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\S\s]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\S\s]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\S\s]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));A(F([["pln",/^\s+/,q," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,q,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w-.:]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^\s"'>]*(?:[^\s"'/>]|\/(?=\s)))/],["pun",/^[/<->]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^\s"'>]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],["lang-css",
/^style\s*=\s*([^\s"'>]+)/i]]),["in.tag"]);A(F([],[["atv",/^[\S\s]+/]]),["uq.val"]);A(B({keywords:N,hashComments:!0,cStyleComments:!0,types:S}),"c cc cpp cxx cyc m".split(" "));A(B({keywords:"null,true,false"}),["json"]);A(B({keywords:P,hashComments:!0,cStyleComments:!0,verbatimStrings:!0,types:S}),["cs"]);A(B({keywords:O,cStyleComments:!0}),["java"]);A(B({keywords:E,hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);A(B({keywords:Q,hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),
["cv","py"]);A(B({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);A(B({keywords:R,hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);A(B({keywords:G,cStyleComments:!0,regexLiterals:!0}),["js"]);A(B({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,true,try,unless,until,when,while,yes",
hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);A(F([],[["str",/^[\S\s]+/]]),["regex"]);window.prettyPrintOne=function(d,r,m){var n=document.createElement("PRE");n.innerHTML=d;m&&L(n,m);M({g:r,i:m,h:n});return n.innerHTML};window.prettyPrint=function(d){function r(){for(var x=window.PR_SHOULD_USE_CONTINUATION?p.now()+250:Infinity;w<n.length&&p.now()<x;w++){var t=n[w],e=t.className;if(0<=e.indexOf("prettyprint")&&(!t.querySelector("ol")||!t.querySelector("ol").classList.contains("linenums"))){e=
e.match(l);var a,b;if(b=!e){b=t;for(var f=void 0,c=b.firstChild;c;c=c.nextSibling){var g=c.nodeType;f=1===g?f?b:c:3===g?V.test(c.nodeValue)?b:f:f}b=(a=f===b?void 0:f)&&"CODE"===a.tagName}b&&(e=a.className.match(l));e&&(e=e[1]);b=!1;for(f=t.parentNode;f;f=f.parentNode)if(("pre"===f.tagName||"code"===f.tagName||"xmp"===f.tagName)&&f.className&&0<=f.className.indexOf("prettyprint")){b=!0;break}b||((b=(b=t.className.match(/\blinenums\b(?::(\d+))?/))?b[1]&&b[1].length?+b[1]:!0:!1)&&L(t,b),k={g:e,h:t,i:b},
M(k))}}w<n.length?setTimeout(r,250):d&&d()}for(var m=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],n=[],z=0;z<m.length;++z)for(var y=0,u=m[z].length;y<u;++y)n.push(m[z][y]);m=q;var p=Date;p.now||(p={now:function(){return+new Date}});var w=0,k,l=/\blang(?:uage)?-([\w.]+)(?!\S)/;r()};window.PR={createSimpleLexer:F,registerLangHandler:A,sourceDecorator:B,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",
PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();