const l = {
    add_new_task : "Add new task",
    edit_task : "Edit task",
    you_cant_add_task_from_chapter : "You can't add task from chapter",
    status_update_success_txt : "Status has been updated successfully.",
    deleting_multiple_contents_will_also_delete_the_nested_contents: "If this item has nested sub-items, then deleting this will also delete sub-items.",
    viewer_error_msg_js: "You are participating as a viewer, You don't have permission to save.",
    add_new_part: "Add New Part",
    cut_js: "Cut",
    paste_js: "Paste",
    eng: "English",
    deleted: "Deleted",
    donot_select_multiseat: "Please do not select multi seat vouchers.",
    select_used_voucher: "Please select used voucher only.",
    edit_js: "Edit ",
    delete_js: "Delete ",
    add_existing_content: "Add Existing Content",
    duplicate_row: "Duplicate Row",
    author_lesson: "Author as Lesson",
    draft_js: "Draft",
    publish_js: "Publish",
    edit_mode: "Lesson Preview",
    import_from_epub: "Import a Lesson Below",
    select_new_content_type: "Select new content type",
    change_type_js: "Change type",
    objective_js: "Objective",
    fact_js: "Fact",
    embeded_content_js: "Embeded content",
    glossary_js: "Glossary",
    customize_saved: "Saved Successfully.",
    unable_save: "Error. Unable to save",
    add_txt : "Add",
    actions_txt : "Actions",
    bug_update : "Bug updated successfully.",
    org_url_exist : "Org Ucertify Url already exists!!",
    logo_validate : "logo must be less than 1MB.",
    logo_res : "logo size must be of maximum 300x100 pixel resolution.",
    image_validate : "Only jpeg, jpg, png, gif, bmp file types are supported.",
    country_update : "Country updated successfully.",
    country_not_updated : "Country not updated.",
    post_update : "Post updated successfully.",
    post_not_updated : "Post not updated.",
    user_deleted  : "The user has been deleted successfully! ",
    user_not_deleted  : "The user cannot be deleted.Please try after some time!",
    first_js_lang : "Js Testing",
    error_while_saving_please_try_again : "Error while saving, please try again",
    do_you_really_want_to_save : "Do you really want to Save?",
    off: "Off",
    lti_success: "Your score has been updated on your LMS.",
    lti_fail: "Score is not updated due to some technical issue.",
    select_an_option_txt : "Select an option",
    updated_please_reload : "Updated, please reload.",
    content_not_deleted_please_try_again : "Unable to delete the content. Please try again.",
    delete_content_with_child : "Item is deleted successfully with its child.",
    error_unable_to_delete : "Error. Unable to delete",
    no_changes_txt : "No changes.",
    content_has_been_added_successfully : "Content has been added successfully.",
    content_has_not_been_added_successfully : "Content has not been added successfully.",
    part_has_been_deleted_successfully : "Part has been deleted successfully.",
    content_has_been_moved_successfully : "Content has been moved successfully.",
    content_has_not_been_moved_successfully : "Content has not been moved successfully.",
    error_unable_to_move : "Error. Unable to move",
    content_level_has_been_changed_successfully : "Content level has been changed successfully.",
    content_level_has_not_been_changed_successfully : "Content level has not been changed successfully.",
    error_unable_to_changed_level : "Error. Unable to changed the level",
    taglist: "Tag List",
    formats: "Formats",
    inline: "Inline",
    bold: "Bold",
    bits: "bold",
    italic: "Italic",
    italics: "italic",
    underline: "Underline",
    underlines: "underline",
    strikethrough: "Strikethrough",
    strikethroughs: "strikethrough",
    superscript: "Superscript",
    superscripts: "superscript",
    subscript: "Subscript",
    subscripts: "subscript",
    small: "Small",
    smalls: "small",
    heading: "Heading",
    heading1: "Heading 1",
    heading2: "Heading 2",
    heading3: "Heading 3",
    heading4: "Heading 4",
    heading5: "Heading 5",
    heading6: "Heading 6",
    newspaper: "Newspaper Font",
    blocks: "Blocks",
    para: "Paragraph",
    div: "Div",
    block: "Blockquote",
    span: "Span",
    code: "Code",
    insnote: "Instructor Note",
    insans: "Instructor Answer",
    alignment: "Alignment",
    left: "Left",
    alignleft: "alignleft",
    center: "Center",
    aligncenter: "aligncenter",
    right: "Right",
    alignright: "alignright",
    justify: "Justify",
    alignjustify: "alignjustify",
    cases: "Cases",
    uppercase: "Uppercase",
    lowercase: "Lowercase",
    titlecase: "Titlecase",
    sentence_case: "Sentence Case",
    toggle_case: "Toggle Case",
    color: "Color",
    success: "Success",
    bsuccess: "b-success",
    warning: "Warning",
    bwarning: "b-warning",
    danger: "Danger",
    bdanger: "b-danger",
    white: "White",
    bwhite: "b-white",
    green: "Green",
    bgreen: "b-green",
    objref: "objref(italic)",
    borange: "b-orange",
    binfo: "b-info",
    bprimary: "b-primary",
    bgcolor: "Background color",
    lsuccess: "Label-Success",
    linfo: "Label-Info",
    lprimary: "Label-Primary",
    ldanger: "Label-Danger",
    lwarning: "Label-Warning",
    list: "List",
    withoutBullet: "Without Bullet",
    numlist: "Numbered list",
    alphlist: "Alphabetical list",
    romanlist: "Roman list",
    numalphlist: "Numeric alpha list",
    bullist: "Bullet list",
    blarlist: "Black arrow bullets",
    bluearlist: "Blue arrow bullets",
    blarbullet: "Blue arrow bullets with gray background",
    blcrcbbullet: "Blue circle bullets",
    bcbwbt: "Blue circle bullet with black text",
    redcrlist: "Red circle list",
    whcrclist: "White circle list",
    tickbull: "Tick Bullet",
    listtype1: "List type 1",
    listtype2: "List type 2",
    listtype3: "List type 3",
    listtype4: "List type 4",
    listtype5: "List type 5",
    listtype6: "List type 6",
    table: "Table",
    deftable: "Default Table",
    smplbortab: "Simple Bordered Table",
    unbortab: "Unbordered Table",
    borbacktab: "Bordered Background Table",
    hrowsbor: "Highlighted Rows Bordered",
    strptab: "Striped Table",
    tabhovdes: "Table Hover Design",
    mulstrp: "Multiple Stripes",
    separate: "Separate",
    grycolor: "Gray color column",
    blueshade: "Blue header with shading table",
    box: "Box",
    panelblue: "Panel Box Blue",
    panelgreen: "Panel Box Green",
    panelsky: "Panel Box Sky-blue",
    panelgrad: "Panel Box gradient",
    block_with_border: "Panel Box with Border",
    blockgrey: "Block in grey background",
    symbols: "Symbols",
    ucsyntax: "UC Syntax",
    indentation: "Indentation",
    clear_formatting: "Clear Formatting",
    wrap_text: "Wrap your text in block element to indent",
    outdent: "outdent",
    removeformat: "removeformat",
    align_content_message: "Wrap your text in block element to align content",
    blue_color:"Blue",
    orange_color:"Orange",
    red_color: "Red",
    golden_brown_color: "Golden Brown",
    black_color: "Black",
    green_color: "Green",
    cyan_color:  "Cyan",
    uc_syntax_format1: "White with number",
    uc_syntax_format2: "White without number",
    uc_syntax_format3: "Black with number",
    uc_syntax_format4: "Black without number",
    line_break1: "Single line Break",
    line_break2: "Double line Break",
    quotes: "Quotes(Sayings)",
    code_block1: "Syntax",
    code_block2: "Black with number",
    code_block3: "Black without number",
    code_block4: "White with number",
    code_block5: "White without number",
    timeline: "Timeline",
    slideshow :"Slideshow",
    panel_success: "Panel Success",
    panel_info: "Panel Info",
    panel_primary: "Panel Primary",
    panel_danger: "Panel Danger",
    panel_warning: "Panel Warning",
    acc_list1: "Accordion List 1",
    acc_list2: "Accordion List 2",
    acc_list3: "Accordion List 3",
    acc_list4: "Accordion List 4",
    inlineAlign: "icomoon-inline",
    headings: "icomoon-heading",
    block_ico: "icomoon-blocks",
    alginments: "icomoon-align",
    case: "icomoon-cases",
    colors: "icomoon-color",
    background: "icomoon-background-color",
    lists: "icomoon-list",
    tables: "icomoon-table",
    boxes: "icomoon-24-px-box",
    symbol: "icomoon-symbols",
    ucsyntaxes: "icomoon-uC-syntax",
    ucfeed: "icomoon-uC-feedback",
    dummyText: "Enter Your Text Here",
    authoring : "Authoring",
    change_view : "Change View",
    render_tag : "Render Tags",
    version_control : "Revision History",
    preview : "Preview",
    remediation : "Remediation",
    back : "Back",
    save_header : "Confirmation",
    save_process : "Please, be patient. We are saving your data...",
    save_confirmation : "Do you want to save this content?",
    cancel : "Cancel",
    done : "Done",
    save_new : "Save as new",
    save : "Save",
    save_success : "Data saved successfully",
    save_success_owner : "Content is successfully saved. Get it published by the Reviewer/Owner to make it visible in the course.",
    save_error : "It seems that the course is not loaded. Please load the course before you save.",
    setting : "Settings",
    add_response : "Add Response",
    add_editable : "Add Editable",
    case_sensetive : "Case Sensitive",
    ignore_spcl_char : "Ignore Special Character",
    multi : "Multiple Correct Answer",
    fill_header : "Fill in the blanks - type",
    fill_text_title : "Fill in the blanks (with text)",
    fill_dropdown_title : "Fill in the blanks (with drop downs)",
    fill_dragdrop_title : "Fill in the blanks (with drag & drop)",
    short_text : "Short Text",
    fill_multiline_title : "Fill in the blanks (with multiline)",
    fill_math_title : "Fill in the blanks (with mathematical equations)",
    fill_text_placeholder : "Write correct answer here",
    fill_text_help1 : "1. To include multiple correct answers, type the answers and separate them with a comma (,).",
    fill_text_help2 : "2. Please do not include any space. Now, go back to the Settings and select Multiple Correct Answers from the drop-down.",
    fill_text_help3 : "3. Use #cm for comma (e.g., 5,000 as 5#cm000, function(a,b) as function(a#cmb)).",
    fill_math_help1 : "1. To make math equation initially, Click f(x) and then insert the equation.",
    fill_math_help2 : "2. To add user Response, place cursor before{*} and Click Add Response.",
    fill_math_help3 : "3. To edit the existing equation, Click Edit.",
    //fill_text_help3 : "Now, go back to Settings and select Multi from the drop-down.",
    fill_dropdown_placeholder : "Write Option here",
    fill_dropdown_help1 : "1. To choose correct answer, select any one radio button from the given options.",
    fill_dropdown_help2 : "2. To choose the display answer, put ‘+’ sign before it. For eg: (+value).",
    fill_dropdown_help3 : "3. To give comma (,) between the text use #cm symbol.",
    drag_single : "Allow single dragging",
    fill_dragdrop_help1 : "1. By default, all answer option is correct.",
    fill_dragdrop_help2 : "2. To make an option incorrect, uncheck the corresponding checkbox.",
    fill_dragdrop_help3 : "3. To give comma (,) between the text use #cm symbol.",
    fill_dragdrop_help4 : "4. To give Vertical bar (|) use #pipe symbol.",
    default_answer : "Default Answer",
    rows : "Rows",
    cols : "Cols",
    fill_multiline_help1 : "By default, all the options provided are correct.",
    matchlist_heading1 : "List 1 heading",
    matchlist_heading2 : "List 2 heading",
    matchlist_normal : "Normal",
    matchlist_dnd : "Drag & Drop",
    shuffle : "Click here to Shuffle",
    add_item : "Add item",
    allow_sort : "Sequence", //"Allow User to Sort",
    in_sentence : "Sentence",
    in_paragraph : "Paragraph",
    go_back : "Go Back",
    goback_header : "Confirmation",
    goback_confirmation : "Do you really want to go to item list?",
    sceneChange_confirmation: "Your changes will be lost. Do you want to save this content ? ",
    show_preview : "Preview",
    xml : "XML",
    back_authoring : "Back to Authoring",
    title : "Title",
    stem : "Stem",
    content : "Content",
    error : "Error",
    playertag : "Player Tag",
    equationeditor : "Equation Editor",
    error_occured : "Something went wrong, Please try again.",
    click_preview : "Click To Preview",
    loading_module : "Loading Module",
    something_wrong : "Something went wrong, Please try again.",
    reload : "Reload",
    search_here : "Search here...",
    all_item : "All Items",
    max_error : "More than 6 options may cause this item to not render properly on a smartphone.",
    reset : "Reset",
    resetDB : "Reset DB",
    calculate_answer : "Calculating Answer",
    add : "Add",
    remove : "Remove",
    correct_answer : "Correct Answer",
    your_answer : "Your Answer",
    correct : "Correct",
    incorrect : "Incorrect",
    select_language : "Language",
    please_wait : "Please, be patient. We are working things up for you. ",
    sequence : "Sequence",
    multi_check : "Multi Check",
    default : "Default",
    heading_correct : "Heading for correct list item",
    heading_all : "Heading for all list item",
    open_doc : "uCertify Team has open this content for editing. Your changes might be lost.",
    getting_diff : "Please, be patient. We are calculating the differences for you.",
    getting_list : "Please, be patient. We are generating the list for you.",
    restore_currect : "Restore Current Version",
    submit : "Submit",
    getting_webpage : "Please, be patient. We are generating the Webpage list for you.",
    getting_docx : "Please, be patient. We are generating the Content in Docx Formatting for you.",
    getting_help : "Please, be patient. We are generating the help for you.",
    warning : "Warning!",
    row_limit : "You have reached the minimum number of rows you can delete.",
    col_limit : "You have reached the minimum number of columns you can delete.",
    del_confirmation : "Are you sure you want to delete it?",
    wrong_value_information : "Values of the row and column should always be multiples of ",
    min_row_col_value : "Insufficient value to make a table; there should be atleast four values.",
    provide_value_suggestion : "Insufficient value to make a table; please increase or decrease the value by 1.",
    totaloption : 'Total number of values available : ',
    max_row_col_error : "More than five rows and five columns may not render properly on a smartphone.",
    create_existing_variable : "Create Existing Variable",
    create_new_variable : "Create New variable",
    update_variable : "Update Variable",
    use_existing_variable : "Use existing variable",
    help : "Help",
    create_variable : "Create Variable",
    all_function_help : "* Do not give a variable name containing space.",
    randInt_function_help : "* Default value will be 1.",
    randint_randfloat_function_help1 : "* This function is used to find a random number between two given numbers.",
    randint_randfloat_function_help2 : "* Do not provide the non-integer value in the minimum and maximum fields.",
    randint_randfloat_function_help3 : "* Minimum value should always be less than the maximum value.",
    randobj_function_help1 : "* This function is used to find a random character or string separated by "+"\",\" (comma).",
    randobj_function_help2 : "* Provide the value like Java, React, Php, and C.",
    custom_function_help1 : "* This function is used to solve any expression.",
    custom_function_help2 : "* Some of the functions take a character/word as an argument so the argument must be passed between the # (hash) symbol.",
    custom_function_help3 : "* If you want to find Intersection, then the argument must be passed like this: math.setIntersect([#a#,#b#],[#a#,#b#,#c#]).",
    custom_function_help4 : "* If you want to find Differentiation, then the argument must be passed like this: math.derivative(#var1*obj1<sup>var2</sup>-var3*obj1+var4#,#obj1#).",
    edit_token: "Highlight correct token",
    edit_template: "Enter text",
    word: "Word",
    sentance: "Sentence",
    paragraph: "Paragraph",
    clear: "Clear",
    no_of_token: "Selected",
    token_highlight: "Token Highlight",
    direction: "Direction:",
    enableline : "Enable-line",
    language: "Language",
    add_testcase: "Add Testcase",
    is_graph : "Is Graph",
    ignore_error: "Ignore Error",
    ignore_formatting: "Ignore Formatting",
    ignore_reset_db: 'Ignore Reset DB',
    pre_tag: "Pre Tag",
    run: "Run",
    run_code: "Run Code",
    html_css_js: "HTML/ CSS/ JS",
    input: "Input",
    output: "Output",
    testcases: "Testcases",
    close: "Close",
    pre: "Pre",
    post: "Post",
    editor: "Editor",
    save_variable : "Save Variables",
    create_steps : "Create Steps",
    plain_text : "Plain text",
    interactive : "Interactive",
    no_validation : "No validation",
    sticky : "Sticky",
    "delete" : "Delete",
    confirm_delete_variable : "If this variable is used in steps it will be treated as text. Are you sure you want to delete it?",
    next : "Next",
    solve : "Solve",
    functions: "Functions",
    Allsymbols: "All Symbols",
    Basic: "Basic",
    xvariables: "x",
    sin: "sin",
    Misc: "Misc",
    Discrete: "Discrete",
    kg: "kg",
    lb: "lb",
    brackets: "Brackets",
    algo_xml: "Algo XML",
    val_variations: "Values variations",
    chem: "Chem",
    tools: "Tools",
    domain: "Domain",
    exam_objective: "Exam Objective",
    web_pages: "Web pages",
    docx_formatting: "Docx Formatting",
    analyze_ebook: "Analyze Ebook Item",
    inline: "Inline",
    bold: "Bold",
    italic: "Italic",
    underline: "Underline",
    strikethrough: "Strikethrough",
    superscript: "Superscript",
    subscript: "Subscript",
    small: "Small",
    subtype: "Tag SubType:",
    showangle: "Show Angle",
    alignment: "Alignment:",
    raw: "RAW",
    html: "HTML",
    css: "CSS",
    js: "JS",
    result: "Result",
    autograde: "Autograde",
    disable: "Disable/Hide",
    editable: "Editable",
    hidden: "Hidden",
    disabled: "Disabled",
    internalScript: "Internal Script",
    externalScript: "External Script",
    detail: "Detail",
    element_name: "Element Name",
    convert: "Convert",
    analyze_content: "Analyze Content",
    analyzing: "Analyzing",
    show_more: "Show more",
    show_less: "Show less",
    task:"Task",
    task_objective:"Task Objective",
    textsnippet:"Text Snippet",
    sectiondetail:"Section Details",
    tags:"Tags",
    item:"Item",
    itemType:"Item Type",
    type:"Type",
    comments:"Comments",
    cognitive_level:"Cognitive Level",
    refer_content:"Refer Content",
    create_equation:"Create Equation",
    help_video:"Help Video",
    diagnostic:"Diagnostic",
    keyboard_shortcut:"Keyboard Shortcut",
    delete_exist_element: "Are you sure you want to delete existing elements?",
    edit_dialog: "Edit Dialog",
    update: "Update",
    add_category: "Add Category",
    import_csv: "Import CSV",
    create_new_question: "Create New Question",
    max: "Max",
    min: "Min",
    step: "step",
    slider: "Slider",
    oops_msg: "Oops! Something went wrong please check your ParseXML Function.",
    minimum: "Minimum",
    maximum: "Maximum",
    step: "Step",
    ignore_grading: "Ignore grading",
    eval_ada1_msg: "1. Press 'CTRL+SHIFT+Enter key' to RUN the code",
    eval_ada2_msg: "2. Press 'CTRL+SHIFT+SPACE key' to goto Input/Output side",
    eval_ada_info: "ADA Information",
    annotationId: "Enter image annotation item ID here",
    annotationPlaceholder: "Enter image annotation title here",
    imageAnnotation: "An annotation player is used to add the image annotation in the middle of the e-book lessons.",
    select_lang: "Please select language",
    show_transcript: "Show transcript",
    audio_recorder: "Audio Recorder",
    starting_message: "Click on record to start recording",
    spoken_label: "What we heard",
    note_label: "Note: ",
    insensitive_message: "Matching is case insensitive.",
    recording_warning: "Recording will end automatically after 15 sec.",
    english_us: "English (United States)",
    english_in: "English (U.K.)",
    italiano: "Italian",
    suomi: "Finnish",
    svenska: "Swedish",
    confirm_label: "Confirm",
    modal_data: "It will override the previous recording. Do you want to continue?",
    no_label: "No",
    yes_label: "Yes",
    browser_support_msg: "Your browser does not support this feature. Please use latest version of chrome browser to use this feature.",
    recording_ended: "Recording ended.",
    no_data_msg: "No recorded data found.",
    matching_msg: "No matching data is found.",
    space_warning: "Do not use more than one space unnecessary.",
    separate_by_quote: "separate with &quot; , &quot",
    pre_code: "pre code",
    write_function_here: "Write your function here...",
    postcode: "post code",
    seperate_by_enter_key: "Separate input by 'enter' key",
    minus_1: "-1",
    case_insensitive: "Case Insensitive",
    partial_matching: "Partial Matching",
    partial_match: "Partial Match",
    special_char: "Special Char",
    input_seperated_comma: "Input seperated by ','",
    ignore_special_char: "Ignore Special Char",
    testcase: "TestCase",
    markPointColor: "Point Color",
    lightGreen: "Light Green",
    black: "Black",
    orange : "Orange",
    select_case_match: "Select case match",
    decimal_position: "please enter the decimal position between 1 to ",
    grid_one_to_ten: "Number Must be between 1 to 10",
    col_less_one : "Column Not allowed less then 1",
    type_one_to_seven: "Please type between 1 to 7",
    row_less_one: "Row Not allowed less then 1",
    type_one_to_ten: "Please type between 1 to 10",
    double_digit: "Double digit not accepted",
    less_one : "Less then 1 not accepted",
    number_from: "Insert number between 0 to ",
    another_option: "Select another option",
    layout_options: "Layout Options",
    row_count: "Row Count",
    col_count: "Column Count",
    empty_field: "Field value can not be empty",
    lock_author_cell: "To lock author shaded cells, it should be part of correct answer",
    delete_graph: 'Click on this button to delete the graph',
    delete_chart: 'Click on this button to delete the last point of the chart',
    ada_graph_msg: 'Press any key on this button to open modalbox to set the point for draw the graph without click on the graph board',
    ada_chart_msg: 'Press any key on this button to open modalbox to set the point for draw the chart without click on the chart board',
    add_chart_msg: 'Click on this button to add the point on the chart',
    edit_graph: 'Click on this button to open modalbox for change the graph view',
    edit_chart: 'Click on this button to open modalbox for change the chart view',
    validate_dialog: 'You have to put the image name',
    ada_message: "use control plus alt plus 1 to open the dialog for perform the task",
    token_message: "Please use ##pt for dot (.) and #cm for comma (,).",
    button_text: 'Shown on the button at the bottom of the intro screen.',
    level_text: 'Level',
    insert_note: 'Insert Note',
    load_more: 'Load More',
    placeholder_text: 'Enter the name of button',
    name_text: 'Name',
    note_placeholder: 'Insert text here',
    level_placeholder: 'Enter the label message',
    knowledge_check: 'This player tag is used to add questions in the middle of the ebook lessons.',
    enter_title: 'Enter the title',
    multi_item_id: 'Enter the comma-separated item id(s)',
    item_id: 'Item ID',
    graded: 'Graded Item(s)',
    coding: 'This player tag is used to test the web module’s XML and display its preview simultaneously in the ebook lessons.',
    simulation: 'This player tag is used to create menu-based questions in Word or Excel, in which only the tabs are working.',
    terminal: 'This player tag is used to add the Linux, DOS, or Java module questions in the middle of the ebook lessons.',
    lablink: 'This player tag is used to add live labs in the mid of ebook lessons which can then be clicked and opened in a new tab.',
    insight: 'This player tag is used to add the 3D chat questions in the middle of the ebook lessons.',
    playground: 'Coding Lab',
    simulation_txt: 'Simulation',
    terminal_txt: 'Terminal',
    livelab: 'Live Lab',
    lab3d: '3D Lab',
    java_txt: 'Java',
    linux_txt: 'Linux',
    dos_txt: 'DOS',
    default_val: 'Enter the default value. Example: dialog_name=options',
    enter_xml: 'Enter the XML',
    simulator_name: 'Simulator Name',
    simulator_place: 'Enter the simulator name. Example: msoffice-msword-2013',
    enter_item: 'Enter the item id',
    embed: 'Embed',
    new_tab: 'New Tab',
    overlay: 'Overlay',
    btn_name: 'Button Name',
    enter_btn_name: 'Enter the button name',
    correct_val: 'Enter the correct value. Example: dialog=fileoptionsdvanced',
    learn_mode: 'Learn Mode',
    audio_des: 'This player tag is used to add audios in the ebook lessons.',
    video_des: 'This player tag is used to add videos in the ebook lessons.',
    audio_txt: 'Audio',
    video_txt: 'Video',
    url_txt: 'URL',
    media_url: 'Enter the media url',
    transcript_id: 'Transcript ID',
    enter_id: 'Enter the transcript id',
    preview_img: 'Image Preview',
    preview_url: 'Enter the image preview url',
    security_info: 'This is required security configuration',
    security_txt: 'Security',
    security_place: "Enter the security data in json format {'token': '45674', 'wID': '89765'}",
    security_title: "Put the security data in json for example {'token': '45674', 'wID': '89765'}.",
    multiple_video: 'Multiple Videos',
    multiple_info: 'All media on this page will be grouped together in a single carousel.',
    add_interval: 'Add Interval',
    interval_txt: 'Interval',
    in_sec: '(In seconds)',
    action_txt: 'Action',
    caption_txt: 'Caption',
    one_num: '1',
    download_info: 'This player tag is used to attach pdf files, word documents, excel files, powerpoint presentations, or any kind of attachment in the ebook lessons.',
    pdf_info: 'This player tag is used to add the pdf files in the ebook lessons.',
    exhibit_info: 'This player tag is used to add an image or a table in a modal box in quizzes or questions.',
    weblink_info: 'This player tag is used to add the “Click to read” link, having an image in its background, in the middle of the ebook lessons, which redirects a user to the new link or web page.',
    download_txt: 'Download',
    exhibit_txt: 'Exhibit',
    pdf_txt: 'PDF',
    weblink_txt: 'Web Link',
    image_txt: 'Image',
    text: 'Text',
    select_img: 'Select an image',
    ms_access: 'MS Access',
    ms_excel: 'MS Excel',
    ms_word: 'MS Word',
    sas_txt: 'SAS',
    zip_txt: 'Zip',
    show_caption: 'Show Button Caption',
    img_show: 'When image will be shown',
    hide_caption: 'Hide Button Caption',
    img_hide: 'When image will be hide',
    btn_txt: 'Button',
    link_txt: 'Link',
    enter_url: 'Enter the url',
    enter_img_url: 'Enter the image url',
    enter_icon_url: 'Enter the image icon url',
    insert_img: 'Insert Image',
    img_alt: 'Image Alt',
    img_desc: "Enter the image's description in brief",
    img_height: 'Enter the image height. Example: 500px',
    frame_height: 'Enter the frame height. Example: 500px',
    frame_ht: 'Frame Height',
    imgage_ht: 'Image Height',
    img_width: 'Image Width',
    enter_img_width: 'Enter the image width. Example: 500px',
    enter_txt: 'Enter the text',
    border_txt: 'Bordered',
    player3d_des: 'A 3D Player tag is used to add images with their descriptions in a 3D structure in the middle of the e-book lessons.',
    snt_des: 'A UC Snt tag is used to add a statement notifying students that more than one option is correct for the given quiz or question.',
    snt_41: 'Each correct answer represents a complete solution. Choose all that apply.',
    snt_40: 'Each correct answer represents a part of the solution. Choose all that apply.',
    snt_39: 'Each correct answer represents a complete solution. Choose three.',
    snt_38: 'Each correct answer represents a part of the solution. Choose three.',
    snt_37: 'Each correct answer represents a complete solution. Choose two.',
    snt_36: 'Each correct answer represents a part of the solution. Choose two.',
    des_txt: 'Description',
    seq_des: 'A UC Seq tag is used to refer the correct and incorrect options in the single/multiple choice questions.',
    enter_seq_title: 'Enter the sequence letter',
    seq_lable: 'Sequence Letter: use a, b, c, d etc. as per the option',
    can_not_del: 'You can not Delete Default Node',
    unable_to_get: 'Unable to get data due to some error.',
    multi_err: 'Multiple item ids are not allowed.',
    invalid_id: 'Invalid Item id.',
    know_check_txt: 'Knowledge Check',
    lab_txt: 'Lab',
    media_txt: 'Media',
    obj3d_txt: '3D Object',
    instruction_txt: 'Instruction',
    opt_ref: 'Option Reference',
    edit_txt: 'Edit',
    list_content: 'List Contents',
    create_new_txt: 'Create New',
    search_item_txt: 'Search Item ID or text',
    no_record: 'No Record Found.',
    scorm_txt: 'Scorm',
    scorm_id: 'Scorm ID',
    scorm_place: 'Enter the scorm transcript id',
    mobile_url: 'Mobile URL',
    mobile_url_place: 'Enter the scorm URL for mobile devices',
    scorm_url: 'Enter the scorm URL',
    width_warning: 'The image width must be in between 100px to 1000px',
    height_warning: 'The image height must be in between 80px to 550px',
    valid_link: 'Please add a valid video link or Check the format for adding the transcript!',
    required_field: 'Please enter all the required fields!',
    vtt_unvalid: 'VTT format is Not valid!',
    vtt_added: 'Transcript ID is added!',
    load_course : 'Please load a course first!',
    asset_not_empty: 'URL can\'t be empty!',
    vtt_exists: 'Transcript is present for this video. ID added!',
    no_title: 'Do not show video title',
    normal_mode: 'Light Mode',
    dark_mode: 'Dark Mode',
    figure_caption_text: 'Figure caption',
    edit_marker_text: 'Edit Marker',
    markers_text: 'Markers',
    upload_media_text: 'Upload Media',
    image_url: 'Image Url',
    image_alt_type: 'Image Alt Text',
    are_you_sure_you_want_to_delete_marker: 'Are you sure you want to delete the marker?',
    add_image_text: 'Add image',
    upload_text: 'Upload',
    file_extension_text: 'File Extensions',
    number_of_files: 'Number of files',
    you_can_upload: '#You can upload upto 10 files only.',
    date_correct_answer_field_placeholder: 'Define The Date For Correct Answer',
    correct_answer_field_placeholder: 'Define The Value For Correct Answer',
    duration: 'Duration',
    vtt: 'VTT',
    enter_vtt: 'Enter VTT Here',
    add_vtt: 'ADD',
    add_transcript_msg: 'Add Transcript',
    edit_transcript_msg: 'Edit Transcript',
    edit_msg: 'Edit',
    parent_guid_found: 'You cannot make changes in a child item. Do you want to open the parent item for making changes?',
    del_row: 'Delete',
    update_child: 'Update Child Items',
    show_child: 'Show Child Item',
    show_all: 'Show all child items',
    generate_item: 'Generate Items',
    plz_sel: 'Please Select',
    csv_file: 'Import .csv file',
    show_all_label: 'Open',
    save_war_msg: 'The current item should be saved first before generating child items',
    generate_items: 'Generate child items',
    already_generated: 'Child items already generated',
    child_not_generated: 'Child items not generated yet',
    new_not_allowed: 'New .csv file cannot be added now, item already created',
    add_option: 'Add Option',
    add_child: 'Add row(s)',
    child_not_selected: 'Child items not selected yet',
    child_update: 'Changes have been made to the parent item. Do you want to update the child items?',
    deletion_not_allowed: 'Child items are created. Deletion is not allowed now',
    update_item: 'Update Item(s)',
    new_row_tooltip: 'New row(s) added. Update child items',
    interval_err: "Video interval can not be more than video duration",
    image_prev_msg: "Image preview cannot be added as video has intervals.",
    video_url_err: "Please add a valid video url",
    delete_warning: 'Do you really want to delete this form block?',
    add_elm: 'Add Elements',
    set_seq: 'Set Sequence',
    pass_elem: 'Password',
    num_elem: 'Number',
    time_elem: 'Time',
    textarea_elem: 'Long Message',
    text_elem: 'Short Message',
    file_elem: 'Upload Image',
    linear_elem: 'Linear Scale',
    select_elem: 'Drop Down',
    chk_elem: 'Checkbox',
    rad_elem: 'Radio',
    date_elem: 'Date',
    add_point: 'Add point',
    set_ans: 'Set Answer',
    ok_btn: 'OK',
    snap_to: 'SnapTo',
    yinterval_val: 'Y (enter multiple values)',
    xinterval_val: 'X (enter multiple values)',
    set_color: 'Set Color',
    primary_color: 'Primary',
    warning_color: 'Warning',
    danger_color: 'Danger',
    default_representation: 'Default representation of chart.',
    xaxis_title: 'X-axis Title',
    yaxis_title: 'Y-axis Title',
    chart_title: 'Chart Title',
    column_label: 'Column',
    line_label: 'Line',
    histogram_label: 'Histogram',
    height_label: 'Height [px]',
    width_label: 'Width [px]',
    chart_label: 'Chart',
    plot_graph: 'Plot Graph',
    xaxis_label: 'X-axis',
    yaxis_label: 'Y-axis',
    xaxis_interval: 'X-axis interval',
    yaxis_interval: 'Y-axis interval',
    width_label1: 'Width',
    height_label1: 'Height',
    axis_label: 'Axis',
    number_line_association: 'Numberline Association',
    numberline_plot: 'Numberline Plot',
    fill_warning: 'Please fill out this field',
    equation: 'Equation',
    both_xy: 'Both X & Y',
    only_x: 'X',
    only_y: 'Y',
    inequality_num: 'Inequality Number Line Equation:',
    equation_type: 'Equation Type',
    standard_form: 'Standard Form : y=m*x+c',
    circle_form: 'Standard Form : (x-x1)^2 + (y-y1)^2 = r^2',
    parabola_form: 'Vertex Form : y=a*(x-h)^2+k',
    sin_form: 'Standard Form : y=a*sin(b*x+c)+d',
    cos_form: 'Standard Form : y=a*cos(b*x+c)+d',
    polygon_type: 'Polygon Type',
    point_graph: 'Point Graph',
    line_graph: 'Line Graph',
    circle_graph: 'Circle Graph',
    ray_graph: 'Ray Graph',
    segment_graph: 'Segment Graph',
    vector_graph: 'Vector Graph',
    parabola_graph: 'Parabola Graph',
    sine_graph: 'Sine Graph',
    cos_graph: 'Cosine Graph',
    polygon_graph: 'Polygon Graph',
    association: 'Association',
    current_item: 'Current Item',
    used_in_items: 'Used In Items',
    file_uploaded: 'File uploaded successfully.',
    html5_not_supported: 'Browser does not support HTML5.',
    upload_valid_csv: 'Please upload a valid .csv file.',
    exact2_column_allowed: 'Exact 2 columns should be present in the .csv file. Upload denied.',
    blank_column_notallowed: 'Blank cell(s) found in the .csv file. Upload denied.',
    min_max_validation: 'Minimum 4 rows and maximum 500 rows are allowed in the .csv file. Upload denied.',
    check_network: 'Something went wrong. Please check your network connection and click the "Generate Items" button again.',
    min4_max500_allowed: 'Minimum 4 rows and maximum 500 rows are allowed for generate the child items.',
    child_items_generated: 'Child items generated successfully.',
    check_net_and_save: 'Something went wrong. Please check your network connection and save the current item.',
    min4_rows_allowed: 'Minimum number of rows should be 4.',
    child_updated: 'Child IDs updated successfully.',
    max500_rows_allowed: 'Maximum number of rows should be 500.',
    check_net_update_ids: 'Something went wrong. Please check your network connection and update the IDs again.',
    fill_required_field: 'Please fill all the required Field! ',
    image_width_range: 'Image width must be between 400px and 600px!',
    edit_image: 'Edit Image',
    image_url: 'Image URL',
    browse: 'Browse',
    image_alt: 'Image Alt',
    image_caption: 'Image Caption',
    image_width: 'Image Width',
    marker_color: 'Marker Color',
    text_align: 'Text Align',
    bottom: 'Bottom',
    on_click: 'On Click',
    mark_symbol: 'Mark Symbol',
    number_marker:'Number Marker',
    plus_marker:'Plus Marker',
    checkmark_marker:'Checkmark Marker',
    cross_marker:'Cross Marker',
    earth_marker:'Earth Marker',
    notification_marker:'Notification Marker',
    radio_marker:'Radio Marker',
    minus_marker:'Minus Marker',
    border: 'Border',
    copy: 'Copy',
    delete_points: 'Delete Points',
    delete_no_of_points: 'To delete the numbers or symbols from the list, delete their mark points.',
    change_image: "Changing Image or Image Width will reposition the markers (Not accurate).\n\n Do you want to reposition markers or reset the data?",
    reposition: 'Reposition',
    delete_confirmation: 'Deleting point will remove its content too! Do you want to delete?',
    copid_paste: ' copied, Click to Paste!',
    point: 'Point',
    deleted_text: ' Deleted!',
    image_err: 'Make Sure all the required fields are non-empty and Image width must be between 400px and 600px!',
    image_alt_text: 'Image Alternative Text ',
    reset_data: 'Do you really want to reset data?',
    delete_row: 'Delete Row',
    delete_column: 'Delete Column',
    min_val: 'Min Value',
    max_val: 'Max Value',
    current_val: 'Current Value',
    correct_val: 'Correct Answer',
    add_slider: 'Add Slider',
    canvas_options: 'Canvas Options',
    cell_width: 'Cell Width',
    multiple_of: 'Multiple of',
    cell_height: 'Cell Height',
    author_shaded: 'Author Shaded',
    lock_shaded_cells: 'Lock shaded cells',
    set_corr_ans: 'Set correct answer(s)',
    method: 'Method',
    set_corr_loc: 'Set Correct Location',
    set_corr_count: 'Set Correct Count',
    you_were_req_to_select: 'You were required to select',
    grid_mark_ans_correct: 'grids to mark the answer correct.',
    hindi_lang: 'Hindi',
    spanish_lang: 'Spanish',
    french_lang: 'French',
    german_lang: 'German',
    japanese_lang: 'Japanese',
    korean_lang: 'Korean',
    drag_drop_set_seq_msg: 'Drag and Drop to set sequence.',
    please_enter_reply_comment : 'Please enter the reply comment',
    exhibit_err: 'Exhibit player does not support this format',	
    embed_player: 'This player tag is used to embed a content.',
    icon_not_blank: 'Icons name should not be blank!',	
    check_net_update_ids: 'Something went wrong. Please check your network connection and update the IDs again.',
    heading_info: "Here, # is the parent (root) element of the tree and it will not be dragged, ## is the child of the parent element and it will also not be dragged, ### is the child of the parent's child element and it can be dragged and dropped.",	
    key_info: "Key|Option text|Icon (Put comma after each line) Where  option text is the label for option of contextmenu list and icon is icon for that label and key is numeric value that helps to create the list option.",	
    note_text: "*Note:",	
    icons_list: "Icons List",	
    hase_icon_3: "### icon",	
    hase_icon_2: "## icon",	
    hase_icon_1: "# icon",	
    no_icons: 'No icons found!',	
    search_icons: 'Search Icons',	
    loading_icons: 'Please wait, Loading Icons...',	
    select_icon: "You can get the icon name by clicking on the Icon list button!",
    light_blue: "Light Blue",
    dark_blue: "Dark Blue",
    peach: "Peach",
    green: "Green",
    purple: "Purple",
    table_width: "Table width",
    themes: "Themes",
    add_row: "Add row",
    add_column: 'Add column',
    upload_data: 'Upload Data',
    hour: 'Hour',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    graph: 'Graph :',
    users: 'Users',
    course_code: 'Course Code',
    iot_graph: 'IOT Graphs',
    from: 'From',
    to: 'To',
    star: '*',
    apply: 'Apply',
    colon: ':',
    both_field_necessary: 'Both Date Field is necessary!',
    load_efficiency: 'Load Efficiency',
    avg_max_speed: 'Average load & max speed',
    recent_fuel: 'Recent Fuel Reading',
    truck_list: 'Truck List',
    show_graph: 'Show Graph',
    get_truck_list: 'Get Truck List',
    no_data_found : 'No data Found!',
    total_users: 'Total Users',
    time_interval : 'Time Interval',
    total_unique_users: 'Total Unique Users',
    total_unique_users_per_day: 'Total Unique Users Per Day',
    load_efficiency_for_truck: 'Load efficiency for Truck id',
    max_speed: 'Max Speed',
    avg_load : 'Average Load',
    fuel_reading: 'Fuel Reading',
    truck_id : 'Truck ID',
    comment_choiceMatrix : 'Use #cm for comma.',
    // dndAuthString.js
    draggable: 'Draggable',
    placeholder: 'Place Holder',
    input_box: 'Input Box',
    checkbox_input: 'Check Box Input',
    multiline_text_box: 'Multiline Text Box',
    radio_inout: 'Radio input',
    select: 'Select',
    select_dropdown: 'Select Dropdown',
    new_menu: 'New Menu',
    clickable: 'Clickable',
    new_label: 'New Label',
    hotspot : 'Hotspot',
    new_steps: 'New Step',
    insert_script: 'Insert Script',
    select_list: 'Select List',
    label: 'Label',
    area_matrix: 'Area Matrix',
    new_pills: 'New Pills',
    base: 'Base',
    choice_matrix: 'Choice Matrix',
    delete_txt: 'Do you want to delete it?',
    select_style: '-- Select Style --',
    heading_arial: 'Heading Arial',
    heading_georgia: 'Heading Georgia',
    heading_cambria: 'Heading Cambria',
    heading_calibri: 'Heading Calibri',
    heading_verdana: 'Heading Verdana',
    heading_roman: 'Heading Times New Roman',
    content_arial: 'Content Arial',
    content_georgia: 'Content Georgia',
    content_cambria: 'Content Camabria',
    content_calibri: 'Content Calibri',
    content_verdana: 'Content Verdana',
    content_roman: 'Content Times New Roman',
    select_class: '-- Select Class --',
    sql_terminal: 'SQL Terminal',
    width_of_draggable: 'Width of Draggable',
    height_of_drggable: 'Height of Draggable',
    top_of_draggable: 'Top of Draggable',
    top: 'Top',
    left: 'Left',
    left_of_drggable: 'Left of Draggable',
    title_of_drggable: 'Title of draggable',
    name_of_draggable: 'Name of draggable',
    border_color: 'Border Color',
    none: 'None',
    black: 'Black',
    gray: 'Gray',
    grp_name: 'Group Name',
    background_image: 'Background Image',
    bg_of_draggble: 'Background image of draggable',
    multiple_drag: 'Multiple Drag',
    invisible: 'Invisible',
    css_style: 'CSS Style',
    css_style_of_txt: 'CSS style of Textbox',
    detail_of_drag: 'Detail of draggable (guid or text)',
    width_of_placeholder: 'Width of Place holder',
    height_of_placeholder: 'Height of Place holder',
    top_of_ph: 'Top of Place holder',
    left_of_ph: 'Left of Place holder',
    tilte_of_ph: 'Title of Place holder',
    name_of_ph : 'Name of Place holder',
    correct_answer_of_ph: 'Correct answer of Place holder',
    default_answer_of_ph: 'Default answer of Place holder',
    css_style_of_ph: 'CSS style of Place holder',
    width_of_input : 'Width of Input box',
    height_of_input: 'Height of Input box',
    top_of_input: 'Top of Input box',
    left_of_input: 'Left of Input box',
    correct_answer_of_input: 'Correct answer of Input box',
    default_ans_of_input: 'Default answer of Input box',
    placeholder_of_ib: 'Place holder of Input box',
    text_box: 'Text box',
    password: 'Password',
    parser: 'Parser',
    parser_of_txt: 'Parser of Textbox',
    sql: 'SQL',
    case_insensitive: 'Case-insensitive',
    multi_crct_answer: 'Multiple Correct Answers',
    css_of_input: 'CSS style of Input box',
    font_style: 'Font Style',
    height_of_multiline: 'Height of Multiline',
    width_of_multiline: 'Width of Multiline',
    top_of_multiline: 'Top of Multiline',
    left_of_multiline: 'Left of Multiline',
    crct_ans_multiline: 'Correct answer of Multiline',
    def_ans_multiline: 'Default answer of Multiline',
    placeholder_multiline: 'Place holder of Multiline',
    parser_of_multiline: 'Parser of Multiline',
    css_class: 'CSS Class',
    width_of_checkbox: 'Width of Checkbox',
    height_of_checkbox: 'Height of Checkbox',
    top_of_checkbox: 'Top of Checkbox',
    left_of_checkbox: 'Left of Checkbox',
    crct_of_chk: 'Correct answer of Checkbox',
    def_of_chk : 'Default answer of checkbox',
    css_of_chk: 'CSS style of checkbox',
    width_of_radio: 'Width of Radio',
    height_of_radio: 'Height of Radio',
    top_of_radio: 'Top of Radio',
    left_of_radio: 'Left of Radio',
    crct_of_radio: 'Correct answer of Radio',
    def_of_radio : 'Default answer of Radio',
    chktype_of_radio: 'Check Type of Radio',
    chk_type: 'Check Type',
    css_style_radio: 'CSS style of Radio',
    width_of_button: 'Width of button',
    height_of_button: 'Height of button',
    top_of_button: 'Top of button',
    left_of_button: 'Left of button',
    value_of_button: 'Value of button',
    class_of_button: 'Class of button',
    value: 'Value',
    class: 'Class',
    css_style_btn: 'CSS style of Button',
    width_of_dropdown: 'Width of dropdown',
    height_of_dropdown: 'Height of dropdown',
    top_of_dropdown: 'Top of dropdown',
    left_of_dropdown: 'Left of dropdown',
    value_of_dropdown: 'Value of dropdown',
    class_of_dropdown: 'Class of dropdown',
    option_of_dropdown: 'Option of dropdown',
    css_style_of_drpdwn: 'CSS style of Dropdown',
    options: 'Options',
    width_of_listbox: 'Width of listbox',
    height_of_listbox: 'Height of listbox',
    top_of_listbox: 'Top of listbox',
    left_of_listbox: 'Left of listbox',
    option_of_listbox: 'Option of listbox',
    select_multiple: 'Select Multiple',
    css_style_of_listbox: 'CSS style of listbox',
    width_of_tabhead: 'Width of tabhead',
    height_of_tabhead: 'Height of tabhead',
    top_of_tabhead: 'Top of tabhead',
    left_of_tabhead: 'Left of tabhead',
    title_of_tabhead: 'Title of tabhead',
    class_of_tabhead: 'Class of tabhead',
    css_style_of_tabhead: 'CSS style of tabhead',
    width_of_image: 'Width of image',
    height_of_image: 'Height of image',
    top_of_image: 'Top of image',
    left_of_image: 'Left of image',
    title_of_image: 'Title of image',
    css_style_of_image: 'CSS style of image',
    bg_of_img: 'Background image of Image',
    width_of_label: 'Width of label',
    height_of_label: 'Height of label',
    top_of_label: 'Top of label',
    left_of_label: 'Left of label',
    title_of_label: 'Title of label',
    border_size: 'Border Size',
    blue: 'Blue',
    red: 'Red',
    bg_color: 'Background Color',
    rich_text: 'Rich Textbox',
    matrix: 'Matrix',
    width_of_area: 'Width of area',
    height_of_area: 'Height of area',
    top_of_area: 'Top of area',
    left_of_area: 'Left of area',
    matrix_of_area: 'Matrix of area',
    crt_of_area: 'Correct Answer of area',
    def_of_area: 'Default Answer of area',
    width_of_menulist: 'Width of menulist',
    height_of_menulist: 'Height of menulist',
    top_of_menulist: 'Top of menulist',
    left_of_menulist: 'Left of menulist',
    matrix_of_menulist: 'Matrix of menulist',
    crt_of_menulist: 'Correct Answer of menulist',
    event_value: 'Events value',
    event_val_menulist: 'Events value of Menulist',
    width_of_hotspot: 'Width of hotspot',
    height_of_hotspot: 'Height of hotspot',
    top_of_hotspot: 'Top of hotspot',
    left_of_hotspot: 'Left of hotspot',
    title_of_hotspot: 'Title of hotspot',
    name_of_hotspot: 'Title of hotspot',
    target_img: 'Target Image',
    hide_target: 'Hide Target',
    target_img_hpt: 'Target Image of Hotspot',
    width_of_click: 'Width of click',
    height_of_click: 'Height of click',
    top_of_click: 'Top of click',
    left_of_click: 'Left of click',
    title_of_tab: 'Title of tab',
    alt_of_image: 'Alt of image',
    bg_of_tab: 'Background image of tab',
    bg_of_step: 'Background image of Step',
    alt_text: 'Alt',
    display: 'Display',
    width_of_base: 'Width of base',
    height_of_base: 'Height of base',
    bg_alt_text: 'Background Alt Text',
    alt_text_base: 'Alt text of Base',
    bg_of_base: 'Background image of Base',
    add_border: 'Add Border',
    width_of_cm: 'Width of Choice Matrix',
    height_of_cm: 'Height of Choice Matrix',
    top_of_cm: 'Top of Choice Matrix',
    left_of_cm: 'Left of Choice Matrix',
    name_of_cm: 'Name of Choice Matrix',
    crt_of_cm: 'Correct Answer of Choice Matrix',
    def_of_cm: 'Default Answer of Choice Matrix',
    css_of_cm: 'CSS style of Choice Matrix',
    on_click: 'On Click',
    on_dbl_click: 'On Double Click',
    on_context: 'On Right Click',
    on_drag_start: 'On Drag Start',
    on_drag: 'On Drag',
    on_drag_end: 'On Drag End',
    on_drop: 'On Drop',
    on_mouse_over: 'On Mouse over',
    on_mouse_up : 'On Mouse Up',
    on_mouse_down: 'On Mouse Down',
    on_change: 'On Change',
    on_focus: 'On Focus',
    on_blur: 'On Blur',
    on_key_up: 'On Key Up',
    on_key_press: 'On Key Press',
    on_key_down: 'On Key Down',
    func_for: 'Function for ',
    old_xml: 'This is old version of XML<br/>If you edit this item it might not work in the Prepkit<br/>For further assistance, please contact New Editor Team.',
    base_steps: 'Base||Steps:',
    timestream: 'Timestream',
    edit_base: 'Base Settings',
    sample_img: 'Sample Image',
    module: 'Module',
    select_instruction: 'Select Module & Click List Contents button for finding all the guid. To select any guid click on the guid.',
    scene: 'Scene',
    intro: 'Intro',
    characters: 'Characters',
    assets: 'Assets',
    chat_windows: 'Chat Windows',
    mission: 'Mission',
    mission_name: 'Mission Name',
    communication: 'Communication',
    animation: 'Animation',
    click_to_select: 'Click to select the ',
    test: "Test",
    learn: "Learn",
    character_voice: 'Character Voice',
    male_one: 'Male 1',
    male_two: 'Male 2',
    male_three: 'Male 3',
    male_four: 'Male 4',
    male: 'Male',
    female: 'Female',
    female_one: 'Female 1',
    female_two: 'Female 2',
    female_three: 'Female 3',
    female_four: 'Female 4',
    female_five: 'Female 5',
    female_six: 'Female 6',
    visibility: 'Visibility',
    asset_visibility: 'Asset Visibility.',
    asset_animation: 'Asset animation.',
    tooltip: 'Tooltip',
    tooltip_txt: 'Tooltip Text',
    onclick_step: 'Onclick Step',
    points: 'Points',
    points_text: 'Provide points for the mission.',
    add_mission: 'Add Mission',
    choose_character: 'Choose character',
    not_visible: 'Not visible',
    voice: 'Voice',
    narrater_voice: 'Narrator Voice',
    conversion_type: 'Conversation Type',
    statement: 'Statement',
    choice: 'Choice',
    item: 'Item',
    multichoice: 'Multi Choice',
    alert: 'Alert',
    autocomplete: 'Auto Complete',
    autocomplete_txt: 'After enabling this it will automatically switch to next step when the statement of this step will end.',
    image_size_txt: 'Select image size more then 256KB and in png format.',
    result_bg: 'Upload Background Image For Result',
    result_info: 'Image displayed on game result screen.',

    image_link: 'Image Link',
    score: 'Score',
    score_value: 'Score Value',
    speech: 'Speech',
    speech_txt: 'Enable speech convertor.',
    speech_input: "After enabling this user will be able to answer by speaking. This feature will work on ucertify.com only.",
    branch_condition: 'Branching Condition',
    no_anim_avail: 'No animation available',
    enter_choice_text: 'Enter Choice Text',
    choice_text: 'Choice Text',
    enter_choice_feedback: 'Enter Choice Feedback',
    feedback_text: 'Feedback text',
    fb_char_name: "Select the feedback character's name.",
    fb_char: 'Feedback Character',
    true: 'True',
    false: 'False',
    step_index: "Step Index",
    step_index_txt: 'Provide the step index to go to that step.',
    new_mission: 'Click to add a new mission.',
    add_choice: 'Add Choice',
    new_step: 'Click to add a new step.',
    add_anim : 'Add Animation',
    animation_play: 'Animation Play',
    dialog: 'Dialog',
    enter_result_title: 'Enter result title',
    result_title: 'Result title',
    result_btn_info: 'If you want to write the result title of your choice, write another title, otherwise skip this step.',
    one_option_correct: 'Only one option can be selected or marked as correct.',
    one_option_require: 'Please set one option as correct answer.',
    delete_textbox: 'Do you want to delete the text box?',
    delete_msg: 'Click the plotted points to delete them.',
    last_delete_msg: '"Click the last plotted point of the item to delete the item!',
    fill_field: 'Please fill out this field.',
    value_gt_zero: 'Value must be greater than 0.',
    enter_number: 'Please enter only number.',
    graph_width: 'Width of graph',
    graph_height: 'Height of graph',
    xaxis_value: 'X-axis value',
    yaxis_value: 'Y-axis value',
    anskey: 'anskey',
    reflection: 'reflection',
    curve_start_point: 'This is the start point of the curve so you cannot delete this point',
    warning_this_for: 'In this case this.for gets undefined and curve does not remove but xml of user answer updated. So prevented xml for being update.',
    last_point: 'You are trying to delete a polygon but either the polygon is not drawn completely or you are trying to delete the polygon by clicking the point, which is not the last point',
    insert_numeric_data: 'Insert numeric data',
    pointy2: 'Point Y2',
    pointx2: 'Point X2',
    pointx1: 'Point X1',
    pointy1: 'Point Y1',
    pointx: 'Point X ',
    pointy: 'Point Y ',
    select_choics: 'Select true or false to indicate if the choice correct or not.',
    select_game_mode: 'Select the game mode.',
    start_button: 'Start Button.',
    set_chr_visiblity: 'Set character visibility.',
    add_chr_nm: 'Provide a character name.',
    chr_voice: "Select the character's voice.",
    type_of_step: 'Select the type of this step',
    guid_value: 'Guid Value',
    value_gt_one: 'Value must be greater than or equals to 1',
    value_gt_interval: 'Value must be greater than interval',
    value_gt_min: 'Value must be greater than min',
    deprecated: 'Association Module is deprecated and will not work!',
    exhibit_err: 'Exhibit player does not support this format',
    open_modal: 'ADA button click to open modal box',
    val_gt_limit: 'Value must be greater than 599!',
    select_one_tool: 'Please select at least one tool.',
    delete_point_msg: '* To delete the points, right click on the points.',
    reset_module: 'Do you want reset the module?',
    ans_correct: "Your's answer is correct!",
    ans_incorrect: "Your's answer is incorrect!",
    shortcuts: 'Shortcuts',
    keys: 'Keys',
    ctrl_z: 'Ctrl + Z or Ctrl + fn + Z',
    undo: 'Undo',
    ctrl_x: 'Ctrl + X or Ctrl + fn + X',
    cut: 'Cut',
    ctrl_y: 'Ctrl + Y or Ctrl + fn + Y',
    redo: 'Redo',
    enter : 'Enter',
    enable_tool: 'Enable the Draw Tool',
    shift_enter: 'Shift + Enter',
    shift_arrow: 'Shift + arrow keys',
    start_stop_tool: 'Start/Stop Drawing by Drawing tool',
    compass_tools: 'Move the Compass components like Radius,center or its Angle / Move the Drawing point',
    locking: 'Shift + L',
    locking_txt: 'Lock the current Point when user is already pressed Enter on current Point',
    draw_key: 'D',
    draw_txt: 'When drawing by scribble tool by key events then fixed the path',
    tab: 'Tab',
    shift_tab: 'Shift + Tab',
    esc: 'Esc',
    focus_next: 'To move towards the next focus points',
    focus_prev: 'To move towards the previous focus points',
    exit_txt: 'To Exit this shortcut window',
    compass_center: 'Compass Center',
    shift_arrow_use : 'Use Shift and arrow keys to move the compass',
    compass_radius: 'Compass Radius, Your Current Radius is ',
    shift_arrow_radius: 'Use Shift and arrow keys to increase or decrease the radius.',
    compass_angle: 'Compass Angle, Your Current Angle is ',
    degree: ' degree',
    compass_draw: 'Compass Draw',
    shift_arrow_draw: ' Use Shift and arrow keys to draw throughout the circumference',
    shift_arrow_angle: 'Use Shift and arrow keys to increase or decrease the radius angle',
    reset_btn: 'Reset Button',
    marking_tools: 'Marking tools',
    removing_tools: 'Removing tools',
    drawing_tools: 'Drawing Tools Container',
    draw_tools: 'Draw tools',
    scribble_tool: 'Scribble tool', 
    line_tool: 'line tool',
    compass_tool: 'compass tool',
    line: 'Line',
    compass: 'Compass',
    scribble: 'Scribble',
    delete_tool: 'Delete tool',
    clear_screen: 'Clear Screen',
    mark_finish_point: 'Mark/Finish Points',
    mark_ans_point: 'Mark/Finish Answer Points',
    mark_pnt: 'Mark Points',
    delete_points: 'Do you want to delete the points?',
    answer_point: 'Answer Points',
    add_show_point: 'Add/Show Point',
    add_finish_point: 'Add/Finish Focus Point',
    add_focus_pnt: 'Add Focus Point',
    def_mode: 'Default Mode',
    access_mode: 'Accessibility Mode',
    configuration: 'Configuration',
    alt_txt_image: 'Alt Text of Image',
    draw_color: 'Drawing Color',
    itemtype_0 : "This task contains the radio buttons and checkboxes for options. The shortcut keys to perform this task are A to H and alt+1 to alt+9.",
    itemtype_1 : "To perform the given task, you have to select an item from one side and place it in front of its correct item on the other side. The shortcut keys to perform this task are Press the Alt+down arrow key to activate. Press the arrow key to navigate through all the items. Copy the left item using the Enter key. Paste the item using the Enter key. If you want to remove any navigated item, then selected that item and press the Delete key to remove for Windows and the Fn+Delete key for Mac.",
    itemtype_4 : "In this type of question, you have to point out the specific area asked in the question. The shortcut keys to perform this task are. The Alt+down arrow key to activate the target. The arrow key to move the target.",
    itemtype_6 : "Here, you have to select the options given in the list. The shortcut keys to perform this task are. The Alt+down arrow key to activate the answer area.  Use the arrow key for navigation. Press the Enter key to select the item. Again, press the Enter key to deselect the item.",
    itemtype_7 : "Here, you have to arrange the options given in the list into their correct order. The shortcut keys to perform this task are. Press the Alt+down arrow key to activate the answer area. Navigate to the item using the arrow key. Press the Enter key to copy the item. Navigate the copied item to the desired position using the arrow keys. Press the Enter key to paste the item. If the item is at its correct position, just press the Enter key to keep that item in sequence. If you want to remove the item from its position, press the Delete key for Windows and the Fn+Delete key for Mac.",
    itemtype_9 : "Here, this type of question contains the select box, text box, and drag and drop boxes. The shortcut keys to perform this task are. Press the Alt+down arrow key to activate the target. Press the arrow key to navigate through all the items. If the selected item is a text box or a select box, it will automatically get focused. If you want to drop the item in the droppable field, navigate to any of the draggable using the Tab key, and press the Enter key to copy the draggable, Now, navigate to any of the droppable field and press the Enter key to drop the copied item. If you want to remove the item from the droppable field, navigate to the droppable field and press the Delete key for Windows and the Fn+Delete key to remove the item.",
    itemtype_14 : "Here, in this type of question, you have to match the item on the left with the correct item on the right by selecting and placing the item to its correct answer. Shortcut key to perform this task are. Press the Alt+down arrow key to activate the target. Press the arrow key to navigate through all the item. Copy the left item using the Enter key. Paste the item using the Enter key. If you want to remove the item, navigate to any of the left side items and press the Delete key to remove for Windows and the Fn+Delete key for Mac.",
    itemtype_26 : "To perform the given task, you have to select and place it in correct item on the. The shortcut keys to perform this task are Press the Alt+down arrow key to activate. Press the arrow key to navigate through all the items. Copy the left item using the Enter key. Paste the item using the Enter key. If you want to remove any navigated item, then selected that item and press the Delete key to remove for Windows and the Fn+Delete key for Mac.",
    itemtype_30 : "Here, in this type of questions, you have to access the range. you can use left arrow key for decreasing the value and right for increasing the value.",
    itemtype_17 : "Here, you have to select the options given in the list. The shortcut keys to perform this task are: Press the tab for navigation. Press the Enter key to select the item and move using the tab key. Again, press the Enter key to deselect the item and place it on the correct option.",
    itemtype_27 : "Here, in this type of questions, you have to identify the correct and incorrect statements by checking the True or False check boxes. The shortcut key to perform the task are. Press Tab for navigation. Press the Enter key for selecting the check box.",
    itemtype_15 : "To perform the given task, you have to select an item from one side and place it in front of its correct item on the other side. The shortcut keys to perform this task are Press the Alt+down arrow key to activate. Press the arrow key to navigate through all the items. Copy the left item using the Enter key. Paste the item using the Enter key. If you want to remove any navigated item, then selected that item and press the Delete key to remove for Windows and the Fn+Delete key for Mac.",
    itemtype_13 : "Here, this type of question contains the terminal. You have to write command to perform this task.",
    itemtype_22 : "Here, this type of question contains the cisco terminal. You have to write command to perform this task.",
    es6_warining: "You are using Internet Explorer, ES6 functionality of javascript will not work!",
};
//window.LANG = l;
export default l;